
export enum SourceConfidence {
  L3 = 'L3', // Authoritative
  L2 = 'L2', // Professional
  L1 = 'L1', // Benchmark
  L0 = 'L0'  // Unknown
}

export enum TaiLevel {
  TAI3 = 'TAI-3', // Strategic/External
  TAI2 = 'TAI-2', // Ops/Internal
  TAI1 = 'TAI-1', // Explore/Internal
  NONE = 'N/A'
}

export interface IndicatorInput {
  name: string;
  sourceName: string;
  missRate?: string; // User input as string
  dataVolume?: string; // User input as string (New)
}

export interface TaiScore {
  level: TaiLevel;
  totalScore: number;
  dimensions: {
    availability: number; // Max 10
    credibility: number;  // Max 10
    businessMatch: number;// Max 10
  };
  details: string[];
}

export interface Metadata {
  // Step 1: Basic
  indi_id: string;
  indi_name_cn: string;
  indi_name_en: string; // Generated by AI
  data_type: string;
  access_level: string;
  upd_freq: string;
  data_unit: string;
  src_name: string;
  update_time: string;

  // Step 2: System Calculation
  data_volume: number;
  miss_rate: number;
  cov_start_dt: string;
  cov_end_dt: string;
  avg_val?: number;
  min_val?: number;
  max_val?: number;
  mid_val?: number;
  like_cnt: number;
  dislike_cnt: number;
  monitor_cnt: number;

  // Step 3: Rule-Based Classification (Deterministic)
  indi_cat: string[]; // Rule-based: Industry, Enterprise, etc.
  gran_level: string; // Rule-based: L1/L2/L3
  src_type: string;   // Rule-based: Gov, Assoc, etc.
  src_conf: SourceConfidence;
  
  // Step 4: AI Generated Context (Gemini)
  involved_company?: string; // Single, Optional (Changed from array)
  industry: string[]; // AI generated involved industries
  
  enhanced_tags: string[]; // 指标增强标签
  data_usage_instructions: string; // 数据使用说明
  main_scene: string[]; // 指标适用场景
  indi_imp: string; // 指标重要性
  indi_def: string; // 指标解释
  
  // Step 5: Manual/Ops
  indi_status: string;
  related_indicators: string[];
  is_exclusive: boolean;
  data_owner: string;
  ver_no: string;
  chg_hist: string;

  // Additional fields used in logic service
  is_data_extraction_involved?: boolean;
  is_industry?: boolean;
}
